{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"webpage_phishing count\",\"webpage_phishing average\",\"webpage_phishing standard_deviation\",\"webpage_phishing combined\",\"Sheet1 (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "Sheet1_2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sheet1 (2)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Sheet1 (2)": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "Sheet1_2.attribute": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sheet1 (2)",
                    "ConceptualProperty": "Attribute"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "attribute": {
                      "State": "Generated"
                    }
                  },
                  {
                    "trait": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "property": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "quality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "characteristic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "feature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "point": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "power": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "Symbols": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "Sheet1_2.average": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sheet1 (2)",
                    "ConceptualProperty": "Average"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "average": {
                      "State": "Generated"
                    }
                  },
                  {
                    "regular": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "usual": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "middling": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "run-of-the-mill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "ordinary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "common": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "standard": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "mode": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "norm": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "mean": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "Sheet1_2.count": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sheet1 (2)",
                    "ConceptualProperty": "Count"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "count": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "Sheet1_2.lower_2s": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sheet1 (2)",
                    "ConceptualProperty": "Lower (2s)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "lower (2s)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "lower (2)": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "lower": {
                      "State": "Generated",
                      "Weight": 0.75
                    }
                  },
                  {
                    "95% confidence lower": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "Sheet1_2.std": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sheet1 (2)",
                    "ConceptualProperty": "STD"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "std": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Standard deviation": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "Sheet1_2.upper2s": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sheet1 (2)",
                    "ConceptualProperty": "Upper(2s)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "upper(2s)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "upper(2)": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "upper": {
                      "State": "Generated",
                      "Weight": 0.75
                    }
                  },
                  {
                    "95% confidence upper": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "Sheet1_2.website": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sheet1 (2)",
                    "ConceptualProperty": "website"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "website": {
                      "State": "Generated"
                    }
                  },
                  {
                    "url": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "site": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "web address": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.571
                    }
                  }
                ]
              },
              "webpage_phishing_average": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing average"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "webpage_phishing average": {
                      "State": "Generated"
                    }
                  },
                  {
                    "webpage_phishing mode": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "webpage_phishing norm": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "webpage_phishing mean": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "webpage_phishing median": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "webpage_phishing_average.attribute": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing average",
                    "ConceptualProperty": "Attribute"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "attribute": {
                      "State": "Generated"
                    }
                  },
                  {
                    "trait": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "property": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "quality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "characteristic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "feature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "point": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "power": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "webpage_phishing_average.value": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing average",
                    "ConceptualProperty": "Value"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "value": {
                      "State": "Generated"
                    }
                  },
                  {
                    "assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "significance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "usefulness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "consequence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "webpage_phishing_average.website": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing average",
                    "ConceptualProperty": "website"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "website": {
                      "State": "Generated"
                    }
                  },
                  {
                    "url": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "site": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "web address": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.571
                    }
                  }
                ]
              },
              "webpage_phishing_combined": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing combined"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "webpage_phishing combined": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "webpage_phishing_combined.attribute": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing combined",
                    "ConceptualProperty": "Attribute"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "attribute": {
                      "State": "Generated"
                    }
                  },
                  {
                    "trait": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "property": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "quality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "feature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "point": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "power": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "Characteristics": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "webpage_phishing_combined.value": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing combined",
                    "ConceptualProperty": "Value"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "value": {
                      "State": "Generated"
                    }
                  },
                  {
                    "assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "significance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "usefulness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "consequence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "webpage_phishing_combined.website": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing combined",
                    "ConceptualProperty": "Website"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "website": {
                      "State": "Generated"
                    }
                  },
                  {
                    "url": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "site": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "web address": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.571
                    }
                  }
                ]
              },
              "webpage_phishing_count": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing count"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "webpage_phishing count": {
                      "State": "Generated"
                    }
                  },
                  {
                    "webpage_phishing amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "webpage_phishing_count.attribute": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing count",
                    "ConceptualProperty": "Attribute"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "attribute": {
                      "State": "Generated"
                    }
                  },
                  {
                    "trait": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "property": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "quality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "characteristic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "feature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "point": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "power": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "webpage_phishing_count.value": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing count",
                    "ConceptualProperty": "Value"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "value": {
                      "State": "Generated"
                    }
                  },
                  {
                    "assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "significance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "usefulness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "consequence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "webpage_phishing_count.website": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing count",
                    "ConceptualProperty": "website"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "website": {
                      "State": "Generated"
                    }
                  },
                  {
                    "url": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "site": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "web address": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.571
                    }
                  }
                ]
              },
              "webpage_phishing_standard_deviation": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing standard_deviation"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "webpage_phishing standard_deviation": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "webpage_phishing_standard_deviation.attribute": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing standard_deviation",
                    "ConceptualProperty": "Attribute"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "attribute": {
                      "State": "Generated"
                    }
                  },
                  {
                    "trait": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "property": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "quality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "characteristic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "feature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "point": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "power": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "webpage_phishing_standard_deviation.column": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing standard_deviation",
                    "ConceptualProperty": "column"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "column": {
                      "State": "Generated"
                    }
                  },
                  {
                    "pilaster": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "pier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "pillar": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "post": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "support": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "stake": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "pole": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "buttress": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "underpinning": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "contribution": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "webpage_phishing_standard_deviation.value": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing standard_deviation",
                    "ConceptualProperty": "Value"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "value": {
                      "State": "Generated"
                    }
                  },
                  {
                    "assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "significance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "usefulness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "consequence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "webpage_phishing_standard_deviation.website": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "webpage_phishing standard_deviation",
                    "ConceptualProperty": "website"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "website": {
                      "State": "Generated"
                    }
                  },
                  {
                    "url": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "site": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "web address": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.571
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "Sheet1_2_has_attribute": {
                "Binding": {
                  "ConceptualEntity": "Sheet1 (2)"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "Sheet1_2.attribute"
                      },
                      "Subject": {
                        "Role": "Sheet1_2"
                      }
                    },
                    "ID": "Sheet1_2_have_attributes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "Sheet1_2": {
                    "Target": {
                      "Entity": "Sheet1_2"
                    }
                  },
                  "Sheet1_2.attribute": {
                    "Target": {
                      "Entity": "Sheet1_2.attribute"
                    }
                  }
                },
                "State": "Generated"
              },
              "Sheet1_2_has_average": {
                "Binding": {
                  "ConceptualEntity": "Sheet1 (2)"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "Sheet1_2.average"
                      },
                      "Subject": {
                        "Role": "Sheet1_2"
                      }
                    },
                    "ID": "Sheet1_2_have_averages",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "Sheet1_2": {
                    "Target": {
                      "Entity": "Sheet1_2"
                    }
                  },
                  "Sheet1_2.average": {
                    "Target": {
                      "Entity": "Sheet1_2.average"
                    }
                  }
                },
                "State": "Generated"
              },
              "Sheet1_2_has_count": {
                "Binding": {
                  "ConceptualEntity": "Sheet1 (2)"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "Sheet1_2.count"
                      },
                      "Subject": {
                        "Role": "Sheet1_2"
                      }
                    },
                    "ID": "Sheet1_2_have_counts",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "Sheet1_2": {
                    "Target": {
                      "Entity": "Sheet1_2"
                    }
                  },
                  "Sheet1_2.count": {
                    "Target": {
                      "Entity": "Sheet1_2.count"
                    }
                  }
                },
                "State": "Generated"
              },
              "Sheet1_2_has_lower_2s": {
                "Binding": {
                  "ConceptualEntity": "Sheet1 (2)"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "Sheet1_2.lower_2s"
                      },
                      "Subject": {
                        "Role": "Sheet1_2"
                      }
                    },
                    "ID": "Sheet1_2_have_lower_2s",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "Sheet1_2": {
                    "Target": {
                      "Entity": "Sheet1_2"
                    }
                  },
                  "Sheet1_2.lower_2s": {
                    "Target": {
                      "Entity": "Sheet1_2.lower_2s"
                    }
                  }
                },
                "State": "Generated"
              },
              "Sheet1_2_has_std": {
                "Binding": {
                  "ConceptualEntity": "Sheet1 (2)"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "Sheet1_2.std"
                      },
                      "Subject": {
                        "Role": "Sheet1_2"
                      }
                    },
                    "ID": "Sheet1_2_have_stds",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "Sheet1_2": {
                    "Target": {
                      "Entity": "Sheet1_2"
                    }
                  },
                  "Sheet1_2.std": {
                    "Target": {
                      "Entity": "Sheet1_2.std"
                    }
                  }
                },
                "State": "Generated"
              },
              "Sheet1_2_has_upper2s": {
                "Binding": {
                  "ConceptualEntity": "Sheet1 (2)"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "Sheet1_2.upper2s"
                      },
                      "Subject": {
                        "Role": "Sheet1_2"
                      }
                    },
                    "ID": "Sheet1_2_have_upper2s",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "Sheet1_2": {
                    "Target": {
                      "Entity": "Sheet1_2"
                    }
                  },
                  "Sheet1_2.upper2s": {
                    "Target": {
                      "Entity": "Sheet1_2.upper2s"
                    }
                  }
                },
                "State": "Generated"
              },
              "Sheet1_2_has_website": {
                "Binding": {
                  "ConceptualEntity": "Sheet1 (2)"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "Sheet1_2.website"
                      },
                      "Subject": {
                        "Role": "Sheet1_2"
                      }
                    },
                    "ID": "Sheet1_2_have_websites",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "Sheet1_2": {
                    "Target": {
                      "Entity": "Sheet1_2"
                    }
                  },
                  "Sheet1_2.website": {
                    "Target": {
                      "Entity": "Sheet1_2.website"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_average_has_attribute": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing average"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_average.attribute"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_average"
                      }
                    },
                    "ID": "webpage_phishing_averages_have_attributes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_average": {
                    "Target": {
                      "Entity": "webpage_phishing_average"
                    }
                  },
                  "webpage_phishing_average.attribute": {
                    "Target": {
                      "Entity": "webpage_phishing_average.attribute"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_average_has_value": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing average"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_average.value"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_average"
                      }
                    },
                    "ID": "webpage_phishing_averages_have_values",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_average": {
                    "Target": {
                      "Entity": "webpage_phishing_average"
                    }
                  },
                  "webpage_phishing_average.value": {
                    "Target": {
                      "Entity": "webpage_phishing_average.value"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_average_has_website": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing average"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_average.website"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_average"
                      }
                    },
                    "ID": "webpage_phishing_averages_have_websites",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_average": {
                    "Target": {
                      "Entity": "webpage_phishing_average"
                    }
                  },
                  "webpage_phishing_average.website": {
                    "Target": {
                      "Entity": "webpage_phishing_average.website"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_combined_has_attribute": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing combined"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_combined.attribute"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_combined"
                      }
                    },
                    "ID": "webpage_phishing_combined_have_attributes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_combined": {
                    "Target": {
                      "Entity": "webpage_phishing_combined"
                    }
                  },
                  "webpage_phishing_combined.attribute": {
                    "Target": {
                      "Entity": "webpage_phishing_combined.attribute"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_combined_has_value": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing combined"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_combined.value"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_combined"
                      }
                    },
                    "ID": "webpage_phishing_combined_have_values",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_combined": {
                    "Target": {
                      "Entity": "webpage_phishing_combined"
                    }
                  },
                  "webpage_phishing_combined.value": {
                    "Target": {
                      "Entity": "webpage_phishing_combined.value"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_combined_has_website": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing combined"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_combined.website"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_combined"
                      }
                    },
                    "ID": "webpage_phishing_combined_have_websites",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_combined": {
                    "Target": {
                      "Entity": "webpage_phishing_combined"
                    }
                  },
                  "webpage_phishing_combined.website": {
                    "Target": {
                      "Entity": "webpage_phishing_combined.website"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_count_has_attribute": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing count"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_count.attribute"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_count"
                      }
                    },
                    "ID": "webpage_phishing_counts_have_attributes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_count": {
                    "Target": {
                      "Entity": "webpage_phishing_count"
                    }
                  },
                  "webpage_phishing_count.attribute": {
                    "Target": {
                      "Entity": "webpage_phishing_count.attribute"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_count_has_value": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing count"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_count.value"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_count"
                      }
                    },
                    "ID": "webpage_phishing_counts_have_values",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_count": {
                    "Target": {
                      "Entity": "webpage_phishing_count"
                    }
                  },
                  "webpage_phishing_count.value": {
                    "Target": {
                      "Entity": "webpage_phishing_count.value"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_count_has_website": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing count"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_count.website"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_count"
                      }
                    },
                    "ID": "webpage_phishing_counts_have_websites",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_count": {
                    "Target": {
                      "Entity": "webpage_phishing_count"
                    }
                  },
                  "webpage_phishing_count.website": {
                    "Target": {
                      "Entity": "webpage_phishing_count.website"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_standard_deviation_has_attribute": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing standard_deviation"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_standard_deviation.attribute"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_standard_deviation"
                      }
                    },
                    "ID": "webpage_phishing_standard_deviations_have_attributes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_standard_deviation": {
                    "Target": {
                      "Entity": "webpage_phishing_standard_deviation"
                    }
                  },
                  "webpage_phishing_standard_deviation.attribute": {
                    "Target": {
                      "Entity": "webpage_phishing_standard_deviation.attribute"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_standard_deviation_has_column": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing standard_deviation"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_standard_deviation.column"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_standard_deviation"
                      }
                    },
                    "ID": "webpage_phishing_standard_deviations_have_columns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_standard_deviation": {
                    "Target": {
                      "Entity": "webpage_phishing_standard_deviation"
                    }
                  },
                  "webpage_phishing_standard_deviation.column": {
                    "Target": {
                      "Entity": "webpage_phishing_standard_deviation.column"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_standard_deviation_has_value": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing standard_deviation"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_standard_deviation.value"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_standard_deviation"
                      }
                    },
                    "ID": "webpage_phishing_standard_deviations_have_values",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_standard_deviation": {
                    "Target": {
                      "Entity": "webpage_phishing_standard_deviation"
                    }
                  },
                  "webpage_phishing_standard_deviation.value": {
                    "Target": {
                      "Entity": "webpage_phishing_standard_deviation.value"
                    }
                  }
                },
                "State": "Generated"
              },
              "webpage_phishing_standard_deviation_has_website": {
                "Binding": {
                  "ConceptualEntity": "webpage_phishing standard_deviation"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "webpage_phishing_standard_deviation.website"
                      },
                      "Subject": {
                        "Role": "webpage_phishing_standard_deviation"
                      }
                    },
                    "ID": "webpage_phishing_standard_deviations_have_websites",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "webpage_phishing_standard_deviation": {
                    "Target": {
                      "Entity": "webpage_phishing_standard_deviation"
                    }
                  },
                  "webpage_phishing_standard_deviation.website": {
                    "Target": {
                      "Entity": "webpage_phishing_standard_deviation.website"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "DateTableTemplate_37643b8d-0b1d-4f09-afd1-a63a958df6c3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bcc41002-0df7-4f51-a040-6768ac64ce46",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "be0b12da-4027-418b-8bf4-11647cc8e1f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4c9e4203-5a9d-4ecd-930e-28c9ee073283",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8f988b04-a3d1-4a95-a727-685a3abc6b92",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fbccd602-38f8-4724-af34-e2a4306269f1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "920eccdc-23f2-4bec-bc12-da251fedfd35",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e841522d-e0c9-48de-9a96-498e4d5a3cbe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "51b75e57-59a2-43f2-8c48-ca747be4dce5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "36297219-d910-4c06-b25a-7383a21a91c2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c24c56fe-b5bd-4686-8d21-619b2a304eb6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0c2d369a-6ed6-41d2-b6a4-264366016e5b",
                "ordinal": 3
              }
            ],
            "lineageTag": "8d21a558-05a9-4795-85db-9dee635d531b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "99f7421c-232b-45e1-add5-7b751fa645f9",
        "partitions": [
          {
            "name": "DateTableTemplate_37643b8d-0b1d-4f09-afd1-a63a958df6c3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "webpage_phishing count",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "website",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63558863-d634-4b3b-9a96-411a4d1ff074",
            "sourceColumn": "website",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "890cf777-eaf8-4705-b75f-822e54e13e59",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc10c580-4c6d-43d1-8034-ab2f25377103",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "16761338-a74e-4548-8f82-7dc746379e27",
        "partitions": [
          {
            "name": "webpage_phishing count",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = MySQL.Database(\"127.0.0.1:3306\", \"webpage_phishing\", [ReturnSingleDatabase=true]),",
                "    webpage_phishing_count = Source{[Schema=\"webpage_phishing\",Item=\"count\"]}[Data],",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(webpage_phishing_count, {\"website\"}, \"Attribute\", \"Value\")",
                "in",
                "    #\"Unpivoted Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "webpage_phishing average",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "website",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8876afe4-f587-4738-9433-aedd946a918a",
            "sourceColumn": "website",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc2359af-c86b-4313-b89f-eb1bf4f26c10",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b9b65736-2b8c-443a-a246-94ff3bc1298b",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e81a5fc1-0a56-47d9-b5be-3b00383f7a31",
        "partitions": [
          {
            "name": "webpage_phishing average",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = MySQL.Database(\"127.0.0.1:3306\", \"webpage_phishing\", [ReturnSingleDatabase=true]),",
                "    webpage_phishing_average = Source{[Schema=\"webpage_phishing\",Item=\"average\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(webpage_phishing_average,null,0,Replacer.ReplaceValue,{\"n_asterisk\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",null,0,Replacer.ReplaceValue,{\"n_hashtag\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",null,0,Replacer.ReplaceValue,{\"n_dollar\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Replaced Value2\", {\"website\"}, \"Attribute\", \"Value\"),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Unpivoted Other Columns\",\"n_dots\",\"dot (.)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"n_hyphen\",\"hyphen (-)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"n_underline\",\"underline (_)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"n_slash\",\"slash (/)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"n_questionmark\",\"questionmark (?)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"n_equal\",\"equal (=)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"n_at\",\"at (@)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"n_and\",\"and (&)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"n_exclamation\",\"exclamation (!)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"n_space\",\"space ( )\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"n_tilde\",\"tilde (~)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"n_comma\",\"comma (,)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Replaced Value14\",\"n_plus\",\"plus (+)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",\"n_asterisk\",\"asterisk (*)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value17\" = Table.ReplaceValue(#\"Replaced Value16\",\"n_hashtag\",\"hashtag (#)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value18\" = Table.ReplaceValue(#\"Replaced Value17\",\"n_dollar\",\"dollar ($)\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value19\" = Table.ReplaceValue(#\"Replaced Value18\",\"n_percent\",\"percent (%)\",Replacer.ReplaceText,{\"Attribute\"})",
                "in",
                "    #\"Replaced Value19\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "webpage_phishing standard_deviation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "website",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de52414b-dfbf-4748-be5c-36b97a0d0b9e",
            "sourceColumn": "website",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6994999-d93d-416a-84bc-1152480e2fc7",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "79d392ad-d842-4dbc-816d-af15e176d48d",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "420eff94-734e-4321-a573-d03411fd1ac8",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "15f8ada1-061c-4618-80b8-55ba93c3785e",
        "partitions": [
          {
            "name": "webpage_phishing standard_deviation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = MySQL.Database(\"127.0.0.1:3306\", \"webpage_phishing\", [ReturnSingleDatabase=true]),",
                "    webpage_phishing_standard_deviation = Source{[Schema=\"webpage_phishing\",Item=\"standard_deviation\"]}[Data],",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(webpage_phishing_standard_deviation, {\"website\"}, \"Attribute\", \"Value\")",
                "in",
                "    #\"Unpivoted Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "webpage_phishing combined",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Website",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32c93209-412c-4498-baf4-a8c477fea30e",
            "sourceColumn": "Website",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fbc255f-328e-4222-ad30-9ce226ba8ad6",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73eecb7d-621c-40ba-b375-e6c627baf17c",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "95db2476-67d9-4f26-8693-b134ddbf1f41",
        "partitions": [
          {
            "name": "webpage_phishing combined",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = MySQL.Database(\"127.0.0.1:3306\", \"webpage_phishing\", [ReturnSingleDatabase=true]),",
                "    webpage_phishing_combined = Source{[Schema=\"webpage_phishing\",Item=\"combined\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(webpage_phishing_combined,{{\"phishing\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"phishing\", \"Website\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"1\",\"Fake\",Replacer.ReplaceText,{\"Website\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"0\",\"Real\",Replacer.ReplaceText,{\"Website\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value1\",{\"URL_S\", \"N_S\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Columns\", {\"Website\"}, \"Attribute\", \"Value\"),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Unpivoted Other Columns\",\"URL\",\"\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"_A\",\"URL\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"NURL\",\"redirections\",Replacer.ReplaceText,{\"Attribute\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"URL\",\"URL length\",Replacer.ReplaceText,{\"Attribute\"})",
                "in",
                "    #\"Replaced Value5\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sheet1 (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "website",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27233fe9-6607-43ca-9d40-ea65b998a492",
            "sourceColumn": "website",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "265cbf73-41bf-4c23-b777-dd3a477126fc",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Average",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0942fe3a-3d53-4453-9b3a-7a38079e9b17",
            "sourceColumn": "Average",
            "summarizeBy": "sum"
          },
          {
            "name": "STD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7352ea68-1a3e-4fe5-8573-60e44803de78",
            "sourceColumn": "STD",
            "summarizeBy": "sum"
          },
          {
            "name": "Lower (2s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9bd10cad-c335-42ba-aaf1-1d515c30f31b",
            "sourceColumn": "Lower (2s)",
            "summarizeBy": "sum"
          },
          {
            "name": "Upper(2s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "84ccd301-9de5-4a47-8686-84edd93c666d",
            "sourceColumn": "Upper(2s)",
            "summarizeBy": "sum"
          },
          {
            "name": "Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a51604d1-e0b4-4d86-84c5-da50f752652d",
            "sourceColumn": "Count",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "17c4da53-f411-4833-a8e5-c1d242c50da2",
        "partitions": [
          {
            "name": "Sheet1 (2)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\suhai\\Data Projects\\How to check if a website is real or fake\\Distance.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"website\", type text}, {\"Attribute\", type text}, {\"Average\", type number}, {\"STD\", type number}, {\"Lower (2s)\", type number}, {\"Upper(2s)\", type number}, {\"Count\", Int64.Type}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column12\", \"Column11\", \"Column10\", \"Column9\", \"Column8\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}